Traceback (most recent call last):
  File "/Users/arunkumar.singh/dynamic_pricing_poc/ml_model/price_recommendation_app.py", line 373, in <module>
    while not initialize_models():
  File "/Users/arunkumar.singh/dynamic_pricing_poc/ml_model/price_recommendation_app.py", line 207, in initialize_models
    model.fit(decisions=decisions, rewards=rewards, contexts=contexts)
  File "/Users/arunkumar.singh/Library/Python/3.9/lib/python/site-packages/mabwiser/mab.py", line 1099, in fit
    self._validate_fit_args(decisions, rewards, contexts)
  File "/Users/arunkumar.singh/Library/Python/3.9/lib/python/site-packages/mabwiser/mab.py", line 1353, in _validate_fit_args
    check_true(self.is_contextual,
  File "/Users/arunkumar.singh/Library/Python/3.9/lib/python/site-packages/mabwiser/utils.py", line 61, in check_true
    raise exception
TypeError: Fitting contexts data requires context policy or parametric learning policy.
